# This workflow will build and push a new container image to Amazon ECR,

on:
  release:
    types: [created]

name: Deploy to Amazon Web Services S3

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    - name: Build npm install
      with:
          node-version: "14.17.1"
      uses: jaid/action-npm-install@v1.2.1
  # uses: Jaid/action-npm-install@9483da054882538350947c4147de4c8adbf0d597
  uses: Jaid/action-npm-install@v1.2.4
